/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Horario extends javax.swing.JFrame {

    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jApellido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRegistrarse1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_backOFF_64px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jApellido.setBackground(new java.awt.Color(255, 255, 255));
        jApellido.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jApellido.setForeground(new java.awt.Color(102, 102, 102));
        jApellido.setText("VER HORARIO");
        jPanel1.add(jApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(252, 98, 70));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 420, 320));

        jButtonRegistrarse1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_OFf.png"))); // NOI18N
        jButtonRegistrarse1.setBorderPainted(false);
        jButtonRegistrarse1.setContentAreaFilled(false);
        jButtonRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarse1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarse1MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "¿Desea Cerrar el Sistema?","EXIT",dialogButton);
            if(result == 0){
                System.exit(0);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButtonRegistrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarse1MouseClicked
      // Define las materias
String[] materias = {
    "Matemáticas", "Física", "Química", "Historia", "Literatura", "Biología",
    "Geografía", "Inglés", "Arte", "Educación Física"
};

// Define los horarios
String[][] horario1 = {
    {"Matemáticas", "Física", "Química"},
    {"Historia", "Literatura", "Biología"},
    {"Geografía", "Inglés", "Arte"},
    {"Educación Física", "Matemáticas", "Física"},
    {"Química", "Historia", "Literatura"}
};

String[][] horario2 = {
    {"Biología", "Geografía", "Inglés"},
    {"Arte", "Educación Física", "Matemáticas"},
    {"Física", "Química", "Historia"},
    {"Literatura", "Biología", "Geografía"},
    {"Inglés", "Arte", "Educación Física"}
};

String[][] horario3 = {
    {"Historia", "Literatura", "Biología"},
    {"Geografía", "Inglés", "Arte"},
    {"Educación Física", "Matemáticas", "Física"},
    {"Química", "Historia", "Literatura"},
    {"Biología", "Geografía", "Inglés"}
};

String[][] horario4 = {
    {"Arte", "Educación Física", "Matemáticas"},
    {"Física", "Química", "Historia"},
    {"Literatura", "Biología", "Geografía"},
    {"Inglés", "Arte", "Educación Física"},
    {"Matemáticas", "Física", "Química"}
};

// Lista de horarios
String[][][] horarios = {horario1, horario2, horario3, horario4};

// Selecciona un horario aleatorio
Random rand = new Random();
int index = rand.nextInt(horarios.length);
String[][] horarioSeleccionado = horarios[index];

// Limpiar el jTextArea antes de mostrar los cursos
jTextArea1.setText("");

// Mostrar el horario seleccionado
String[] dias = {"Lunes", "Martes", "Miércoles", "Jueves", "Viernes"};
jTextArea1.append("\nHorario Semanal:\n");
for (int i = 0; i < dias.length; i++) {
    jTextArea1.append(dias[i] + ": ");
    for (int j = 0; j < horarioSeleccionado[i].length; j++) {
        jTextArea1.append(horarioSeleccionado[i][j]);
        if (j < horarioSeleccionado[i].length - 1) {
            jTextArea1.append(", ");
        }
    }
    jTextArea1.append("\n");
}
    }//GEN-LAST:event_jButtonRegistrarse1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellido;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonRegistrarse1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
