/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import AppPackage.AnimationClass;
import Class.Estudiantes;
import Class.Profesor;
import Class.User;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Login extends javax.swing.JFrame {
    private static ArrayList<User> usuarios = new ArrayList<>();
    private static ArrayList<Estudiantes> estudiantes = new ArrayList<>();
        public static ArrayList<Estudiantes> getestudiantes() {
        return estudiantes;
    }
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPIngreso = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPmenu = new javax.swing.JPanel();
        jLabelHorario = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jLabelinformacion = new javax.swing.JLabel();
        jLabelprofesores = new javax.swing.JLabel();
        jCurso = new javax.swing.JLabel();
        jInformacion = new javax.swing.JLabel();
        jHorario = new javax.swing.JLabel();
        jProfesores = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        jLabelLupa = new javax.swing.JLabel();
        jRegistrarse = new javax.swing.JLabel();
        jApellido = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jUsuario = new javax.swing.JLabel();
        jContraseña = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jButtonRegistrarse = new javax.swing.JButton();
        jNosotros = new javax.swing.JLabel();
        jinfo = new javax.swing.JLabel();
        jButtonSee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jPIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jPIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 30));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Password:");
        jPIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, -1));

        jLabel2.setBackground(new java.awt.Color(238, 112, 82));
        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("User:");
        jPIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_96px_2.png"))); // NOI18N
        jPIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 120));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(150, 150, 150));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPIngreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Globe_32px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Key_32px.png"))); // NOI18N
        jPIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 40));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Ingrese Usuario");
        jTextField2.setBorder(null);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPIngreso.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 180, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_customer_32px_1.png"))); // NOI18N
        jPIngreso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, -1, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(252, 98, 70));
        jButton4.setText("Registrarse");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPIngreso.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, 30));

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPmenu.setBackground(new java.awt.Color(255, 255, 255));
        jPmenu.setForeground(new java.awt.Color(255, 255, 255));
        jPmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPmenuMouseClicked(evt);
            }
        });
        jPmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Clock_96px.png"))); // NOI18N
        jLabelHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHorarioMouseClicked(evt);
            }
        });
        jPmenu.add(jLabelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 360, 200, 160));

        jLabelCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Handshake_96px.png"))); // NOI18N
        jLabelCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCursoMouseClicked(evt);
            }
        });
        jPmenu.add(jLabelCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 200, 160));

        jLabelinformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelinformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Today_96px.png"))); // NOI18N
        jLabelinformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelinformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelinformacionMouseClicked(evt);
            }
        });
        jPmenu.add(jLabelinformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 360, 200, 160));

        jLabelprofesores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelprofesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Idea_96px.png"))); // NOI18N
        jLabelprofesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelprofesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelprofesoresMouseClicked(evt);
            }
        });
        jPmenu.add(jLabelprofesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 200, 160));

        jCurso.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jCurso.setForeground(new java.awt.Color(252, 98, 70));
        jCurso.setText("Curso");
        jPmenu.add(jCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, -1, -1));

        jInformacion.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jInformacion.setForeground(new java.awt.Color(252, 98, 70));
        jInformacion.setText("Informacion");
        jPmenu.add(jInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, -1, -1));

        jHorario.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jHorario.setForeground(new java.awt.Color(252, 98, 70));
        jHorario.setText("Horario");
        jPmenu.add(jHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, -1, -1));

        jProfesores.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jProfesores.setForeground(new java.awt.Color(252, 98, 70));
        jProfesores.setText("Profesores");
        jPmenu.add(jProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, -1, -1));

        jTextBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jTextBuscar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        jTextBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jTextBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBuscar.setText("Buscar...");
        jTextBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jTextBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextBuscarMouseClicked(evt);
            }
        });
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        jPmenu.add(jTextBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 190, 40));

        jLabelLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_32px_2.png"))); // NOI18N
        jPmenu.add(jLabelLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, -1, 40));

        jRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        jRegistrarse.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jRegistrarse.setForeground(new java.awt.Color(252, 98, 70));
        jRegistrarse.setText("Registrarse");
        jPmenu.add(jRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, -1));

        jApellido.setBackground(new java.awt.Color(255, 255, 255));
        jApellido.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jApellido.setForeground(new java.awt.Color(102, 102, 102));
        jApellido.setText("Apellido");
        jPmenu.add(jApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, -1, -1));

        jNombre.setBackground(new java.awt.Color(255, 255, 255));
        jNombre.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jNombre.setForeground(new java.awt.Color(102, 102, 102));
        jNombre.setText("Nombre");
        jPmenu.add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, -1, -1));

        jTextFieldApellido.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldApellido.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(252, 98, 70));
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPmenu.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 330, 210, 40));

        jTextFieldNombre.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombre.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(252, 98, 70));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPmenu.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 150, 210, 40));

        jUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jUsuario.setText("Usuario");
        jPmenu.add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, -1, -1));

        jContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jContraseña.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jContraseña.setText("Contraseña");
        jPmenu.add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldUsuario.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(252, 98, 70));
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPmenu.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 150, 210, 40));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldContraseña.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(252, 98, 70));
        jPasswordFieldContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPmenu.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 330, 210, 40));

        jButtonRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrarse_OFF.png"))); // NOI18N
        jButtonRegistrarse.setBorderPainted(false);
        jButtonRegistrarse.setContentAreaFilled(false);
        jButtonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrarse_ON.png"))); // NOI18N
        jButtonRegistrarse.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrarse_ON.png"))); // NOI18N
        jButtonRegistrarse.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrarse_ON.png"))); // NOI18N
        jButtonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarseMouseClicked(evt);
            }
        });
        jPmenu.add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 420, -1, -1));

        jNosotros.setBackground(new java.awt.Color(255, 255, 255));
        jNosotros.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jNosotros.setForeground(new java.awt.Color(252, 98, 70));
        jNosotros.setText("Sobre Nosotros");
        jPmenu.add(jNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, -1));

        jinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captura de pantalla 2024-06-19 180128.png"))); // NOI18N
        jPmenu.add(jinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, 610, 410));

        jButtonSee.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSee.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pngwing.com (1).png"))); // NOI18N
        jButtonSee.setBorder(null);
        jButtonSee.setContentAreaFilled(false);
        jButtonSee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeeMouseClicked(evt);
            }
        });
        jPmenu.add(jButtonSee, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, 40));

        getContentPane().add(jPmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         try{
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea Cerrar el Sistema?","EXIT",dialogButton);
        if(result == 0){
            System.exit(0);
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        AnimationClass izquierda1 = new AnimationClass();
        izquierda1.jLabelXLeft(1100, 20, 4, 10, jRegistrarse);
        
        AnimationClass izquierda2 = new AnimationClass();
        izquierda2.jLabelXLeft(1100, 80, 4, 10, jNombre);
        
        AnimationClass izquierda3 = new AnimationClass();
        izquierda3.jTextFieldXLeft(1100, 80, 4, 10, jTextFieldNombre);
        
        AnimationClass izquierda4 = new AnimationClass();
        izquierda4.jLabelXLeft(1100, 80, 4, 10, jApellido);
        
        AnimationClass izquierda5 = new AnimationClass();
        izquierda5.jTextFieldXLeft(1100, 80, 4, 10, jTextFieldApellido);
        
        AnimationClass izquierda6 = new AnimationClass();
        izquierda6.jLabelXLeft(1100, 530, 4, 10, jUsuario);
        
        AnimationClass izquierda7 = new AnimationClass();
        izquierda7.jTextFieldXLeft(1100, 530, 4, 10, jTextFieldUsuario);
        
        AnimationClass izquierda8 = new AnimationClass();
        izquierda8.jButtonXLeft(1100, 340, 4, 10, jButtonRegistrarse);
        
        AnimationClass izquierda9 = new AnimationClass();
        izquierda9.jLabelXLeft(1100, 530, 4, 10, jContraseña);
        
        AnimationClass izquierda10 = new AnimationClass();
        izquierda10.jPasswordFieldXLeft(1100, 530, 4, 10, jPasswordFieldContraseña);
        
        AnimationClass derecha1 = new AnimationClass();
        derecha1.jLabelXRight(10, 1100, 4, 10, jNosotros);
        
        AnimationClass izquierda22 = new AnimationClass();
        izquierda22.jLabelXRight(80, 1100, 4, 10, jinfo);
        
        AnimationClass derecha = new AnimationClass();
        derecha.jLabelXRight(20, 1100, 4, 10, jLabelCurso);

AnimationClass derecha2 = new AnimationClass();
derecha2.jLabelXRight(100, 1100, 4, 10, jCurso); 

AnimationClass derecha3 = new AnimationClass();
derecha3.jLabelXRight(470, 1100, 4, 10, jLabelprofesores);

AnimationClass derecha4 = new AnimationClass();
derecha4.jLabelXRight(540, 1100, 4, 10, jProfesores);

AnimationClass derecha5 = new AnimationClass();
derecha5.jLabelXRight(20, 1100, 4, 10, jLabelHorario);

AnimationClass derecha6 = new AnimationClass();
derecha6.jLabelXRight(100, 1100, 4, 10, jHorario);

AnimationClass derecha7 = new AnimationClass();
derecha7.jLabelXRight(470, 1100, 4, 10, jLabelinformacion);

AnimationClass derecha8 = new AnimationClass();
derecha8.jLabelXRight(540, 1100, 4, 10, jInformacion);

AnimationClass derecha9 = new AnimationClass();
derecha9.jLabelXRight(270, 1100, 4, 10, jLabelLupa);

AnimationClass derecha10 = new AnimationClass();
derecha10.jTextFieldXRight(310, 1100, 4, 10, jTextBuscar);


        
  
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTextBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextBuscarMouseClicked
        jTextBuscar.setText("");
    }//GEN-LAST:event_jTextBuscarMouseClicked

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    String nombreUsuario = jTextField2.getText();
    String contraseña = new String(jPasswordField1.getPassword());

    // Verificar si el usuario está registrado
    boolean usuarioEncontrado = false;
    for (User usuario : usuarios) {
        if (usuario.getNombre_usuario().equals(nombreUsuario) && usuario.getContrasenia().equals(contraseña)) {
            usuarioEncontrado = true;

	AnimationClass izquierda1 = new AnimationClass();
        izquierda1.jLabelXLeft(1100, 20, 4, 10, jLabelCurso);
        
        AnimationClass izquierda2 = new AnimationClass();
        izquierda2.jLabelXLeft(1100, 100, 4, 10, jCurso); 
        
        AnimationClass izquierda3 = new AnimationClass();
        izquierda3.jLabelXLeft(1100, 470, 4, 10, jLabelprofesores);
        
        AnimationClass izquierda4 = new AnimationClass();
        izquierda4.jLabelXLeft(1100, 540, 4, 10, jProfesores);
        
        AnimationClass izquierda5 = new AnimationClass();
        izquierda5.jLabelXLeft(1100, 20, 4, 10, jLabelHorario);
        
        AnimationClass izquierda6 = new AnimationClass();
        izquierda6.jLabelXLeft(1100, 100, 4, 10, jHorario);
        
        AnimationClass izquierda7 = new AnimationClass();
        izquierda7.jLabelXLeft(1100, 470, 4, 10, jLabelinformacion);
        
        AnimationClass izquierda8 = new AnimationClass();
        izquierda8.jLabelXLeft(1100, 540, 4, 10, jInformacion);
        
        AnimationClass izquierda9 = new AnimationClass();
        izquierda9.jLabelXLeft(1100, 270, 4, 10, jLabelLupa);
        
        AnimationClass izquierda10 = new AnimationClass();
        izquierda10.jTextFieldXLeft(1100, 310, 4, 10, jTextBuscar);
        
        AnimationClass derecha11 = new AnimationClass();
        derecha11.jLabelXRight(20, 1100, 4, 10, jRegistrarse);
        
        AnimationClass derecha12 = new AnimationClass();
        derecha12.jLabelXRight(80, 1100, 4, 10, jNombre);
        
        AnimationClass derecha13 = new AnimationClass();
        derecha13.jTextFieldXRight(80, 1100, 4, 10, jTextFieldNombre);
        
        AnimationClass derecha14 = new AnimationClass();
        derecha14.jLabelXRight(80, 1100, 4, 10, jApellido);
        
        AnimationClass derecha15 = new AnimationClass();
        derecha15.jTextFieldXRight(80, 1100, 4, 10, jTextFieldApellido);
        
        AnimationClass derecha16 = new AnimationClass();
        derecha16.jLabelXRight(530, 1100, 4, 10, jUsuario);
        
        AnimationClass derecha17 = new AnimationClass();
        derecha17.jTextFieldXRight(530, 1100, 4, 10, jTextFieldUsuario);
        
        AnimationClass derecha18 = new AnimationClass();
        derecha18.jButtonXRight(340, 1100, 4, 10, jButtonRegistrarse);
        
        AnimationClass derecha19 = new AnimationClass();
        derecha19.jLabelXRight(530, 1100, 4, 10, jContraseña);
        
        AnimationClass derecha20 = new AnimationClass();
        derecha20.jPasswordFieldXRight(530, 1100, 4, 10, jPasswordFieldContraseña);
        

            break;
        }
    }

    // Mostrar mensaje según el resultado
    if (usuarioEncontrado) {
        JOptionPane.showMessageDialog(this, "Usuario encontrado. Bienvenido " + "'" +nombreUsuario + "'");
    } else {
        JOptionPane.showMessageDialog(this,"Usuario o contrasenia incorrecta, usuario " + "'" +nombreUsuario + "'" +" no encontrado. O por favor, regístrese primero.");
    }
    
    jTextField2.setText("");
    jPasswordField1.setText("");
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarseMouseClicked
    String nombreUsuario = jTextFieldUsuario.getText();
    String contraseña = new String(jPasswordFieldContraseña.getPassword());
    String nombre = jTextFieldNombre.getText();
    String apellido = jTextFieldApellido.getText();

    // Verificar si alguno de los campos está vacío
    if (nombreUsuario.isEmpty() || contraseña.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios. Por favor, complete todos los campos.");
        return; // Salir del método si algún campo está vacío
    }

    // Verificar si el nombre de usuario ya está registrado
    boolean nombreUsuarioExistente = false;
    for (User usuario : usuarios) {
        if (usuario.getNombre_usuario().equals(nombreUsuario)) {
            nombreUsuarioExistente = true;
            break;
        }
    }

    // Mostrar mensaje según el resultado
    if (nombreUsuarioExistente) {
        JOptionPane.showMessageDialog(this, "El nombre de usuario " + "'" + nombreUsuario + "'" + " ya está registrado. Por favor, elija otro.");
    } else {
        // Crear un nuevo objeto Usuario
        User nuevoUsuario = new User(nombreUsuario, contraseña);

        // Agregar el usuario al ArrayList
        usuarios.add(nuevoUsuario);
        
        //Agregar Estudiante
        Estudiantes estudiante = new Estudiantes(nombre, apellido);
        estudiantes.add(estudiante);

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Bienvenido " + "'" + nombreUsuario + "'" + " Usuario registrado exitosamente.");
    }

    // Limpiar los campos después del registro
    jTextFieldUsuario.setText("");
    jPasswordFieldContraseña.setText("");
    jTextFieldNombre.setText("");
    jTextFieldApellido.setText("");
    
    }//GEN-LAST:event_jButtonRegistrarseMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        User usuario = new User("admin","123");
        usuarios.add(usuario);
    }//GEN-LAST:event_formWindowOpened

    private void jLabelinformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelinformacionMouseClicked
        AnimationClass derecha1 = new AnimationClass();
        derecha1.jLabelXRight(20, 1100, 4, 10, jLabelCurso);

        AnimationClass derecha2 = new AnimationClass();
        derecha2.jLabelXRight(100, 1100, 4, 10, jCurso);

        AnimationClass derecha3 = new AnimationClass();
        derecha3.jLabelXRight(470, 1100, 4, 10, jLabelprofesores);

        AnimationClass derecha4 = new AnimationClass();
        derecha4.jLabelXRight(540, 1100, 4, 10, jProfesores);

        AnimationClass derecha5 = new AnimationClass();
        derecha5.jLabelXRight(20, 1100, 4, 10, jLabelHorario);

        AnimationClass derecha6 = new AnimationClass();
        derecha6.jLabelXRight(100, 1100, 4, 10, jHorario);

        AnimationClass derecha7 = new AnimationClass();
        derecha7.jLabelXRight(470, 1100, 4, 10, jLabelinformacion);

        AnimationClass derecha8 = new AnimationClass();
        derecha8.jLabelXRight(540, 1100, 4, 10, jInformacion);

        AnimationClass derecha9 = new AnimationClass();
        derecha9.jLabelXRight(270, 1100, 4, 10, jLabelLupa);

        AnimationClass derecha10 = new AnimationClass();
        derecha10.jTextFieldXRight(310, 1100, 4, 10, jTextBuscar);
        
        AnimationClass izquierda21 = new AnimationClass();
        izquierda21.jLabelXLeft(1100, 10, 4, 10, jNosotros);
        
        AnimationClass izquierda22 = new AnimationClass();
        izquierda22.jLabelXLeft(1100, 80, 4, 10, jinfo);
        
        
        

    }//GEN-LAST:event_jLabelinformacionMouseClicked

    private void jLabelCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCursoMouseClicked
        CURSO curso = new CURSO();
        dispose();
        curso.setVisible(true);
    }//GEN-LAST:event_jLabelCursoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Creación de 10 instancias de tipo Estudiantes
        Estudiantes estudiante1 = new Estudiantes("Laura", "Martínez");
        Estudiantes estudiante2 = new Estudiantes("Pedro", "Gómez");
        Estudiantes estudiante3 = new Estudiantes("Ana", "Sánchez");
        Estudiantes estudiante4 = new Estudiantes("Luis", "Fernández");
        Estudiantes estudiante5 = new Estudiantes("María", "López");
        Estudiantes estudiante6 = new Estudiantes("Carlos", "Pérez");
        Estudiantes estudiante7 = new Estudiantes("Elena", "Hernández");
        Estudiantes estudiante8 = new Estudiantes("Jorge", "Rodríguez");
        Estudiantes estudiante9 = new Estudiantes("Sofía", "García");
        Estudiantes estudiante10 = new Estudiantes("Miguel", "Ramírez");

        // Agregar estas instancias a la lista de estudiantes en la clase Login
        Login.getestudiantes().add(estudiante1);
        Login.getestudiantes().add(estudiante2);
        Login.getestudiantes().add(estudiante3);
        Login.getestudiantes().add(estudiante4);
        Login.getestudiantes().add(estudiante5);
        Login.getestudiantes().add(estudiante6);
        Login.getestudiantes().add(estudiante7);
        Login.getestudiantes().add(estudiante8);
        Login.getestudiantes().add(estudiante9);
        Login.getestudiantes().add(estudiante10);

    }//GEN-LAST:event_formWindowActivated

    private void jLabelprofesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprofesoresMouseClicked
        Profesores profesores = new Profesores();
        dispose();
        profesores.setVisible(true);
    }//GEN-LAST:event_jLabelprofesoresMouseClicked

    private void jPmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPmenuMouseClicked

    private void jButtonSeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeeMouseClicked
        AnimationClass izquierda1 = new AnimationClass();
        izquierda1.jLabelXLeft(1100, 20, 4, 10, jLabelCurso);
        
        AnimationClass izquierda2 = new AnimationClass();
        izquierda2.jLabelXLeft(1100, 100, 4, 10, jCurso); 
        
        AnimationClass izquierda3 = new AnimationClass();
        izquierda3.jLabelXLeft(1100, 470, 4, 10, jLabelprofesores);
        
        AnimationClass izquierda4 = new AnimationClass();
        izquierda4.jLabelXLeft(1100, 540, 4, 10, jProfesores);
        
        AnimationClass izquierda5 = new AnimationClass();
        izquierda5.jLabelXLeft(1100, 20, 4, 10, jLabelHorario);
        
        AnimationClass izquierda6 = new AnimationClass();
        izquierda6.jLabelXLeft(1100, 100, 4, 10, jHorario);
        
        AnimationClass izquierda7 = new AnimationClass();
        izquierda7.jLabelXLeft(1100, 470, 4, 10, jLabelinformacion);
        
        AnimationClass izquierda8 = new AnimationClass();
        izquierda8.jLabelXLeft(1100, 540, 4, 10, jInformacion);
        
        AnimationClass izquierda9 = new AnimationClass();
        izquierda9.jLabelXLeft(1100, 270, 4, 10, jLabelLupa);
        
        AnimationClass izquierda10 = new AnimationClass();
        izquierda10.jTextFieldXLeft(1100, 310, 4, 10, jTextBuscar);
        
        AnimationClass derecha11 = new AnimationClass();
        derecha11.jLabelXRight(20, 1100, 4, 10, jRegistrarse);
        
        AnimationClass derecha1 = new AnimationClass();
        derecha1.jLabelXRight(10, 1100, 4, 10, jNosotros);
        
        AnimationClass izquierda22 = new AnimationClass();
        izquierda22.jLabelXRight(80, 1100, 4, 10, jinfo);
        
        AnimationClass derecha = new AnimationClass();
        derecha.jLabelXRight(20, 1100, 4, 10, jRegistrarse);
        
        AnimationClass derecha12 = new AnimationClass();
        derecha12.jLabelXRight(80, 1100, 4, 10, jNombre);
        
        AnimationClass derecha13 = new AnimationClass();
        derecha13.jTextFieldXRight(80, 1100, 4, 10, jTextFieldNombre);
        
        AnimationClass derecha14 = new AnimationClass();
        derecha14.jLabelXRight(80, 1100, 4, 10, jApellido);
        
        AnimationClass derecha15 = new AnimationClass();
        derecha15.jTextFieldXRight(80, 1100, 4, 10, jTextFieldApellido);
        
        AnimationClass derecha16 = new AnimationClass();
        derecha16.jLabelXRight(530, 1100, 4, 10, jUsuario);
        
        AnimationClass derecha17 = new AnimationClass();
        derecha17.jTextFieldXRight(530, 1100, 4, 10, jTextFieldUsuario);
        
        AnimationClass derecha18 = new AnimationClass();
        derecha18.jButtonXRight(340, 1100, 4, 10, jButtonRegistrarse);
        
        AnimationClass derecha19 = new AnimationClass();
        derecha19.jLabelXRight(530, 1100, 4, 10, jContraseña);
        
        AnimationClass derecha20 = new AnimationClass();
        derecha20.jPasswordFieldXRight(530, 1100, 4, 10, jPasswordFieldContraseña);
        
        

        
        
        
    }//GEN-LAST:event_jButtonSeeMouseClicked

    private void jLabelHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHorarioMouseClicked
        Horario horario = new Horario();
        dispose();
        horario.setVisible(true);
    }//GEN-LAST:event_jLabelHorarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JButton jButtonSee;
    private javax.swing.JLabel jContraseña;
    private javax.swing.JLabel jCurso;
    private javax.swing.JLabel jHorario;
    private javax.swing.JLabel jInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelLupa;
    private javax.swing.JLabel jLabelinformacion;
    private javax.swing.JLabel jLabelprofesores;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNosotros;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JLabel jProfesores;
    private javax.swing.JLabel jRegistrarse;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JLabel jinfo;
    // End of variables declaration//GEN-END:variables
}
