/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import AppPackage.AnimationClass;
import Class.Profesor;
import Class.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Profesores extends javax.swing.JFrame {
    private static ArrayList<Profesor> profes = new ArrayList<>();
    public static ArrayList<Profesor> getprofes() {
        return profes;
    }
    private String obtenerListaProfesores() {
    StringBuilder listaProfesores = new StringBuilder();
    for (Profesor profe : profes) {
        listaProfesores.append(profe.getNombre()).append(" ").append(profe.getApellido()).append("\n");
    }
    return listaProfesores.toString();
}
    /**
     * Creates new form Profesores
     */
    public Profesores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jApellido = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jApellido1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jButtonRegistrarse1 = new javax.swing.JButton();
        jButtonRegistrarse2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_backOFF_64px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_BACK_on_64px_1.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 10, 480));

        jApellido.setBackground(new java.awt.Color(255, 255, 255));
        jApellido.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jApellido.setForeground(new java.awt.Color(102, 102, 102));
        jApellido.setText("Nombre");
        jPanel1.add(jApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombre.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(252, 98, 70));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 40));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(252, 98, 70));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 410, 330));

        jApellido1.setBackground(new java.awt.Color(255, 255, 255));
        jApellido1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jApellido1.setForeground(new java.awt.Color(102, 102, 102));
        jApellido1.setText("Apellido");
        jPanel1.add(jApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jTextFieldNombre1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombre1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        jTextFieldNombre1.setForeground(new java.awt.Color(252, 98, 70));
        jTextFieldNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 98, 70)));
        jPanel1.add(jTextFieldNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 210, 40));

        jButtonRegistrarse1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_OFf.png"))); // NOI18N
        jButtonRegistrarse1.setBorderPainted(false);
        jButtonRegistrarse1.setContentAreaFilled(false);
        jButtonRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarse1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscar_ON.png"))); // NOI18N
        jButtonRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarse1MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 130, 40));

        jButtonRegistrarse2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/añadir_OFF.png"))); // NOI18N
        jButtonRegistrarse2.setBorderPainted(false);
        jButtonRegistrarse2.setContentAreaFilled(false);
        jButtonRegistrarse2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarse2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/añadir_ON.png"))); // NOI18N
        jButtonRegistrarse2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/añadir_ON.png"))); // NOI18N
        jButtonRegistrarse2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/añadir_ON.png"))); // NOI18N
        jButtonRegistrarse2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarse2MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonRegistrarse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 130, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButtonRegistrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarse1MouseClicked
         // Obtener la lista de profesores como cadena de texto
    String listaProfesores = obtenerListaProfesores();
    
    // Mostrar la lista en jTextArea1
    jTextArea1.setText(listaProfesores);
        
    }//GEN-LAST:event_jButtonRegistrarse1MouseClicked

    private void jButtonRegistrarse2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarse2MouseClicked
    String nombreprofe = jTextFieldNombre.getText();
    String apellidoprofe = jTextFieldNombre1.getText();

    // Verificar si los campos están vacíos
    if (nombreprofe.isEmpty() || apellidoprofe.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
    // Verificar si el usuario está registrado
    boolean profeEncontrado = false;
    for (Profesor profe : profes) {
        if (profe.getNombre().equals(nombreprofe) && profe.getApellido().equals(apellidoprofe)) {
            profeEncontrado = true;
            break;
        }
    }

    // Mostrar mensaje según el resultado
    if (profeEncontrado) {
        JOptionPane.showMessageDialog(this, "Profesor ya registrado");
    } else {
        Profesor profe = new Profesor(nombreprofe, apellidoprofe);
        profes.add(profe);
        JOptionPane.showMessageDialog(this, "Profesor registrado, bienvenido " + "'" + nombreprofe + "'");
    }

    jTextFieldNombre.setText("");
    jTextFieldNombre1.setText("");
}

    
    }//GEN-LAST:event_jButtonRegistrarse2MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "¿Desea Cerrar el Sistema?","EXIT",dialogButton);
            if(result == 0){
                System.exit(0);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       setState(Login.ICONIFIED);
    }//GEN-LAST:event_jButton4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Creación de 10 instancias de tipo Profesor
        Profesor profe1 = new Profesor("Juan", "Pérez");
        Profesor profe2 = new Profesor("María", "González");
        Profesor profe3 = new Profesor("Carlos", "Rodríguez");
        Profesor profe4 = new Profesor("Ana", "Martínez");
        Profesor profe5 = new Profesor("Luis", "Hernández");
        Profesor profe6 = new Profesor("Laura", "López");
        Profesor profe7 = new Profesor("José", "García");
        Profesor profe8 = new Profesor("Marta", "Sánchez");
        Profesor profe9 = new Profesor("David", "Ramírez");
        Profesor profe10 = new Profesor("Elena", "Torres");

        // Agregar estas instancias a la lista profes
        profes.add(profe1);
        profes.add(profe2);
        profes.add(profe3);
        profes.add(profe4);
        profes.add(profe5);
        profes.add(profe6);
        profes.add(profe7);
        profes.add(profe8);
        profes.add(profe9);
        profes.add(profe10);

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellido;
    private javax.swing.JLabel jApellido1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonRegistrarse1;
    private javax.swing.JButton jButtonRegistrarse2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    // End of variables declaration//GEN-END:variables
}
